@URL = http://localhost:9000

### Get USER
GET {{URL}}/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJ1c2VyTWVycCIsImlhdCI6MTc3Mjc5Mjk2MCwiZXhwIjoxNzczMzk3NzYwfQ.NuQQjLRxUoM7ay-7EJhQnjOFC9Fw0GEhln381iuGAmI

### Put USER
PUT {{URL}}/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJ1c2VyTWVycCIsImlhdCI6MTc3Mjc5Mjk2MCwiZXhwIjoxNzczMzk3NzYwfQ.NuQQjLRxUoM7ay-7EJhQnjOFC9Fw0GEhln381iuGAmI

{
  "username": "userMerp",
  "password": "um1234"
}


### Get DOC
GET {{URL}}/doctors/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJEb2NwaW1teSIsInNwZWNpYWxpemF0aW9uIjoiRE9DNCIsImlhdCI6MTc3Mjc5NzM1MSwiZXhwIjoxNzczNDAyMTUxfQ.hKZb3Xcy_-pWXDUiFRbmB6Rv31CMYjmpCfDgzsOLpQE


### Put DOC
PUT {{URL}}/doctors/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJEb2NwaW1teSIsInNwZWNpYWxpemF0aW9uIjoiRE9DNCIsImlhdCI6MTc3Mjc5NzM1MSwiZXhwIjoxNzczNDAyMTUxfQ.hKZb3Xcy_-pWXDUiFRbmB6Rv31CMYjmpCfDgzsOLpQE

{
  "username": "DocpimmyNew",
  "password": "dm1234"
}